int valid_op_c (char*);
int valid_op (char, char);
int valid_digt (char);
int valid_numeros (char*, char);
int valid_numeros_f(char*, int);
int valid_numeros_s (char*);
int valid_cpf (char*);
void limpa_buffer (void);
int verif_bissexto (int);
int verif_data (int, int, int);
int valid_data (char*);
int valid_letra (char);
int valid_nome (char*);
int valid_email (char*);
int valid_cnpj (char*);
int valid_cod_barras (char*);
char* centralizar_texto(char*, int, int);
char* input (void);
char* duplica (char*);
char* peg_dia (void);
char* peg_mes (void);
char* peg_ano (void);
char* peg_hora (void);
char* peg_minuto (void);
char* peg_segundo (void);
char* inst_data (void);
char* inst_hora (void);
void trat_nome (char*);
void trat_cpf_entr (char*);
void trat_cpf_said (char*);
void trat_cel_entr (char*);
void trat_cel_said (char*);
void trat_cnpj_entr (char*);
void trat_cnpj_said (char*);
int cancel (char*);
int cpf_zero (char*);
void recebe_cpf_zero (char*);
int cnpj_zero (char*);
void recebe_cnpj_zero (char*);
int cod_barras_zero (char*);
void recebe_cod_barras_zero (char*);
void trat_dat_ent (char*);
void trat_dat_said (char*);
int compara_datas (char*, char*);
int compara_datas_relat (char*, char*, char*);
int compara_float (char*, char*);
int verif_array (int, int[], int);